
[build]
  command = "chmod +x ./netlify-build.sh && ./netlify-build.sh"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

[[redirects]]
  from = "/login"
  to = "/login"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
